import { useEffect,useState } from 'react';
import { Link,useNavigate } from 'react-router-dom';
import { ArrowRight,FileText,FileEdit,CalendarClock,CheckCircle2,Landmark,ShieldCheck,AlertTriangle } from 'lucide-react';
import { PageHeader } from '@/components/layout/PageHeader';
import { Card,CardContent } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Textarea } from '@/components/ui/Input';
import { MetricCard } from '@/components/ui/MetricCard';
import { Skeleton } from '@/components/ui/State';
import { Tooltip } from '@/components/ui/Tooltip';
import { api } from '@/services/api';
import { user } from '@/services/mockData';
import type { ActivitySummary } from '@/types';
const examples=['Why hasn’t the road near my house been repaired?','How many public school teachers were hired in 2025?','What is the status of my driving licence application?'];
export function DashboardPage(){const navigate=useNavigate();const[query,setQuery]=useState('');const[activity,setActivity]=useState<ActivitySummary|null>(null);const[loading,setLoading]=useState(true);const[touched,setTouched]=useState(false);useEffect(()=>{api.getActivity().then(a=>{setActivity(a);setLoading(false)})},[]);const submit=()=>{setTouched(true);if(query.trim().length<10)return;navigate(`/app/ask/results?q=${encodeURIComponent(query.trim())}`)};const h=new Date().getHours();const greeting=h<12?'Good morning':h<17?'Good afternoon':'Good evening';const metrics=[{label:'Active RTIs',value:activity?.active??'—',icon:FileText,tone:'blue' as const,sub:'Awaiting response'},{label:'Drafts',value:activity?.drafts??'—',icon:FileEdit,tone:'gray' as const,sub:'Not yet filed'},{label:'Upcoming deadlines',value:activity?.upcomingDeadlines??'—',icon:CalendarClock,tone:'amber' as const,sub:'Within 30 days'},{label:'Completed requests',value:activity?.completed??'—',icon:CheckCircle2,tone:'green' as const,sub:'Closed'}];return <div><PageHeader title={`${greeting}, ${user.name.split(' ')[0]}`} description="Your civic information workspace at a glance."/>
<div className="mb-7 grid gap-5 xl:grid-cols-[1fr_320px]"><Card className="overflow-hidden border-blue-100"><div className="border-b border-blue-100 bg-[linear-gradient(135deg,#EFF6FF,#fff_60%)] px-6 py-5"><div className="flex items-center justify-between gap-4"><div><p className="civic-kicker">Start an RTI journey</p><h2 className="mt-1 text-xl font-black text-slate-900">What information do you need?</h2><p className="mt-1 text-sm text-slate-500">Describe your issue in plain language. CiviLens will help you find the right place to ask.</p></div><div className="hidden rounded-xl bg-white p-3 text-blue-700 shadow-sm sm:block"><Landmark className="h-6 w-6"/></div></div></div><CardContent className="pt-5"><Textarea value={query} onChange={e=>setQuery(e.target.value)} onBlur={()=>setTouched(true)} placeholder="e.g. Why hasn’t the road near my house been repaired?" rows={4} invalid={touched&&query.trim().length<10} className="resize-none"/>{touched&&query.trim().length<10&&<p className="mt-2 text-xs font-semibold text-red-600">Please describe your issue in at least 10 characters.</p>}<div className="mt-4 flex flex-wrap gap-2">{examples.map(ex=><button key={ex} onClick={()=>setQuery(ex)} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-left text-xs font-semibold text-slate-600 transition hover:border-blue-200 hover:bg-blue-50 hover:text-blue-700">{ex}</button>)}</div><div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2 text-xs text-slate-400"><ShieldCheck className="h-4 w-4 text-blue-600"/>Recommendations are for guidance; verify before filing.</div><Button onClick={submit}>Find the right department <ArrowRight className="h-4 w-4"/></Button></div></CardContent></Card>
<div className="civic-panel-dark p-5"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-blue-200">Attention</p><div className="mt-4 flex items-start gap-3"><div className="rounded-lg bg-amber-400/10 p-2 text-amber-300"><AlertTriangle className="h-5 w-5"/></div><div><p className="font-bold">1 deadline approaching</p><p className="mt-1 text-xs leading-5 text-blue-100/65">Your active RTI response window needs attention.</p><Link to="/app/deadlines" className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-white">Open deadline tracker <ArrowRight className="h-3.5 w-3.5"/></Link></div></div></div></div>
<div className="mb-4 flex items-center gap-2"><h2 className="text-lg font-black">Your RTI activity</h2><Tooltip content="A summary of your current applications, drafts and deadlines."/></div><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{metrics.map(m=><MetricCard key={m.label} label={m.label} value={loading?<Skeleton className="h-7 w-12"/>:m.value} sub={m.sub} icon={<m.icon className="h-5 w-5"/>} tone={m.tone}/>)}</div>
<div className="mt-8 grid gap-4 md:grid-cols-3"><QuickLink to="/app/my-rtis" title="View your RTIs" desc="See every application, status and timeline." icon={FileText}/><QuickLink to="/app/transparency" title="Explore transparency" desc="Understand department responsiveness before you file." icon={Landmark}/><QuickLink to="/app/appeal" title="Appeal guidance" desc="Understand what to do if a response does not arrive." icon={CheckCircle2}/></div></div>}
function QuickLink({to,title,desc,icon:Icon}:{to:string;title:string;desc:string;icon:typeof FileText}){return <Link to={to}><Card hoverable className="h-full p-5"><div className="flex items-start gap-4"><div className="rounded-xl bg-blue-50 p-3 text-blue-700"><Icon className="h-5 w-5"/></div><div><h3 className="flex items-center gap-1.5 font-bold">{title}<ArrowRight className="h-3.5 w-3.5 text-slate-400"/></h3><p className="mt-1 text-sm leading-6 text-slate-500">{desc}</p></div></div></Card></Link>}
