import { Link } from 'react-router-dom';
import { ArrowRight, BarChart3, Building2, CalendarClock, CheckCircle2, FileEdit, Gavel, Globe2, Landmark, MessageSquareText, Scale, ShieldCheck, Sparkles, FileText } from 'lucide-react';
import { Navbar } from '@/components/layout/Navbar';
import { Button } from '@/components/ui/Button';

const journey=[
 ['01','Describe','Tell CiviLens what information you need in your own words.',MessageSquareText],
 ['02','Find','Get a department and PIO recommendation with confidence.',Building2],
 ['03','Understand','Review public transparency indicators before filing.',BarChart3],
 ['04','Draft','Turn your question into a structured RTI application.',FileEdit],
 ['05','Track','Keep the 30-day response window visible and actionable.',CalendarClock],
 ['06','Act','Understand the First Appeal path if you need it.',Gavel],
] as const;

export function LandingPage(){return <div className="min-h-screen bg-[#F8FAFC] text-slate-900"><Navbar/>
<section className="relative overflow-hidden border-b border-slate-200 bg-white"><div className="absolute inset-0 civic-grid opacity-60"/><div className="absolute right-[-10%] top-[-15%] h-[520px] w-[520px] rounded-full bg-blue-100/50 blur-3xl"/><div className="relative mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 lg:grid-cols-[1.02fr_.98fr] lg:px-8 lg:py-24">
<div className="flex flex-col justify-center"><div className="mb-6 flex items-center gap-3"><span className="inline-flex items-center gap-2 rounded-full border border-blue-200 bg-blue-50 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[.12em] text-blue-800"><ShieldCheck className="h-3.5 w-3.5"/>Citizen-first platform</span><span className="hidden text-xs font-medium text-slate-400 sm:inline">Built for the RTI journey</span></div><h1 className="max-w-3xl text-5xl font-black leading-[1.02] tracking-[-.045em] sm:text-6xl lg:text-[70px]">Making government information <span className="text-blue-700">easier to navigate.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600">CiviLens helps citizens understand where to ask, how departments respond, how to draft an RTI, when a response is due, and what to do next.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link to="/app/ask"><Button size="lg">Start with your question <ArrowRight className="h-5 w-5"/></Button></Link><a href="#how"><Button size="lg" variant="outline">Explore the platform</Button></a></div><div className="mt-9 grid max-w-xl grid-cols-3 border-y border-slate-200 py-4"><div><p className="text-xs font-bold text-slate-400">FOCUS</p><p className="mt-1 text-sm font-bold">RTI guidance</p></div><div className="border-l border-slate-200 pl-4"><p className="text-xs font-bold text-slate-400">DESIGN</p><p className="mt-1 text-sm font-bold">Citizen-first</p></div><div className="border-l border-slate-200 pl-4"><p className="text-xs font-bold text-slate-400">PURPOSE</p><p className="mt-1 text-sm font-bold">Transparency</p></div></div></div>
<div className="relative flex items-center"><div className="absolute -left-5 top-8 hidden h-16 w-16 rounded-full border border-blue-200 bg-white lg:block"/><div className="civic-panel-dark relative w-full overflow-hidden p-5 sm:p-7"><div className="absolute right-0 top-0 h-40 w-40 bg-blue-400/10 blur-2xl"/><div className="flex items-center justify-between border-b border-white/10 pb-5"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-blue-200">CIVILENS CIVIC INTELLIGENCE</p><p className="mt-1 text-xs text-blue-100/60">Decision support for your RTI journey</p></div><div className="rounded-lg border border-white/10 bg-white/5 p-2"><Landmark className="h-5 w-5 text-blue-200"/></div></div><div className="mt-6 rounded-xl border border-white/10 bg-white/[.06] p-4"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-blue-200">Your question</p><p className="mt-2 text-sm font-medium leading-6 text-white">“Why hasn’t the road near my house been repaired?”</p></div><div className="my-4 flex justify-center"><div className="rounded-full border border-blue-300/20 bg-blue-500/10 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-blue-200">Analysis complete</div></div><div className="rounded-xl bg-white p-4 text-slate-900 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">Recommended department</p><p className="mt-1 text-lg font-extrabold">Municipal Administration</p><p className="mt-1 text-xs text-slate-500">Local infrastructure & road maintenance</p></div><div className="text-right"><p className="text-2xl font-black text-blue-700">92%</p><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">confidence</p></div></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-[92%] rounded-full bg-blue-600"/></div><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-lg bg-slate-50 p-3"><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Avg. response</p><p className="mt-1 font-extrabold">18 days</p></div><div className="rounded-lg bg-slate-50 p-3"><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Within 30 days</p><p className="mt-1 font-extrabold">87%</p></div></div></div><div className="mt-5 flex items-center gap-2 text-[10px] text-blue-100/60"><ShieldCheck className="h-3.5 w-3.5"/>Verify recommendations before filing</div></div></div></div></section>

<section id="how" className="border-b border-slate-200 bg-[#F8FAFC] py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="civic-kicker">How CiviLens works</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">A complicated process, turned into a clear sequence.</h2><p className="mt-4 leading-7 text-slate-600">The interface keeps the important decision in front of you and moves the complexity into the background.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{journey.map(([num,title,desc,Icon])=><div key={num} className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-[0_4px_18px_-14px_rgba(15,23,42,.45)] transition hover:-translate-y-1 hover:border-blue-200"><div className="flex items-center justify-between"><span className="text-4xl font-black text-blue-100 group-hover:text-blue-200">{num}</span><div className="rounded-xl bg-slate-100 p-3 text-blue-700"><Icon className="h-5 w-5"/></div></div><h3 className="mt-6 font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{desc}</p></div>)}</div></div></section>

<section id="journey" className="border-b border-slate-200 bg-white py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="civic-kicker">The civic journey</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Know what happens next.</h2><p className="mt-4 leading-7 text-slate-600">CiviLens connects discovery, public accountability, drafting and follow-through in one continuous workspace.</p><div className="mt-8 rounded-2xl border border-blue-100 bg-blue-50/60 p-5"><div className="flex items-start gap-3"><Scale className="mt-0.5 h-5 w-5 text-blue-700"/><div><p className="font-bold text-blue-950">Guidance, not legal advice</p><p className="mt-1 text-sm leading-6 text-slate-600">CiviLens helps explain the process and prepare information. Users should verify details before filing.</p></div></div></div></div><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 sm:p-6"><div className="grid gap-3 sm:grid-cols-2">{[['01','Ask','Describe the information you need.'],['02','Discover','See the likely department and PIO.'],['03','Inspect','Review transparency indicators.'],['04','Draft','Prepare a formal RTI document.'],['05','Track','Monitor the response window.'],['06','Appeal','Understand the next procedural step.']].map(([n,t,d])=><div key={n} className="flex gap-4 rounded-xl border border-slate-200 bg-white p-4"><div className="text-sm font-black text-blue-700">{n}</div><div><p className="font-bold">{t}</p><p className="mt-1 text-xs leading-5 text-slate-500">{d}</p></div></div>)}</div></div></div></div></section>

<section id="trust" className="bg-[#102A5C] py-20 text-white"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-200">Why CiviLens</p><h2 className="mt-3 text-4xl font-black tracking-tight">Built around the citizen, not the bureaucracy.</h2><p className="mt-5 leading-7 text-blue-100/75">CiviLens turns scattered RTI decisions into a guided experience while keeping transparency and verification visible at every step.</p></div><div className="grid gap-3 sm:grid-cols-2"><Trust icon={Globe2} title="Public information, clearer" text="Surface useful context around departments and responsiveness."/><Trust icon={FileText} title="Formal when it matters" text="Keep the drafting experience closer to an official document than a chat screen."/><Trust icon={CalendarClock} title="Deadlines stay visible" text="Make the statutory response window something citizens can actually understand."/><Trust icon={CheckCircle2} title="Every recommendation is explainable" text="Show confidence and reasoning instead of hiding decisions behind a black box."/></div></div></div></section>

<footer className="border-t border-slate-200 bg-white py-10"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-4 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><Logo/><div className="flex gap-6 text-sm font-semibold text-slate-500"><a href="#how">How it works</a><a href="#journey">RTI journey</a><Link to="/app">Dashboard</Link></div></div><div className="border-t border-slate-100 pt-5 text-xs leading-5 text-slate-400">CiviLens provides guidance and drafting assistance. It is not a government portal and does not file RTI applications on your behalf. Please verify recommendations before submitting.</div></div></footer>
</div>}
function Trust({icon:Icon,title,text}:{icon:typeof Globe2,title:string,text:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.06] p-5"><Icon className="h-5 w-5 text-blue-200"/><p className="mt-4 font-bold">{title}</p><p className="mt-2 text-sm leading-6 text-blue-100/65">{text}</p></div>}
